[[constraint]]
  name = "github.com/bitrise-io/go-utils"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-tools/go-xcode"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/kballard/go-shellquote"
